name: Deploy to Lambda

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          mkdir package
          pip install --platform manylinux2014_aarch64 --target=package --implementation cp --python-version 3.11 --only-binary=:all: --upgrade -r requirements.txt

      - name: Zip
        run: |
          cd package
          zip -r ../my_deployment_package.zip .
          cd ..
          zip my_deployment_package.zip lambda_function.py

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: scrapeBindella
          zip_file: my_deployment_package.zip